@startuml
!theme plain

object "invoke_agent executor : Span\nrun.iterations=5\niteration=5\nsignal=TaskCompleted" as AR
object "chat qwen : Span" as C1
object "execute_tool read : Span" as ET1
object "execute_tool edit : Span" as ET2
object "chat qwen : Span" as C2
object "execute_tool test : Span" as ET3

AR *-- C1
AR *-- ET1
AR *-- ET2
AR *-- C2
AR *-- ET3
@enduml
